name: "CI"
on:
  push:
  pull_request:
    branches:
      - "main"
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - "ubuntu-latest"
          - "macos-latest"
          - "windows-latest"
        ruby-version:
          - "3.2"
          - "3.3"
          - "truffleruby-head"
          - "head"
        exclude:
          - { os: "windows-latest", ruby-version: "truffleruby-head" }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/checkout@v4"
      - uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          # This CI job does not compile extensions so no need to install a toolchain (which takes 1+ min)
          windows-toolchain: none
      - name: "Enable global frozen string literals for head"
        if: matrix.ruby-version == 'head'
        run: "echo RUBYOPT=--enable-frozen-string-literal >> $GITHUB_ENV"
      - run: "bundle exec rake"
